name: cadence/flow-emulator 

on:
  workflow_dispatch:
    inputs:
      CADENCE_HASH:
        description: "Cadence repo commit hash"
        type: string
      FLOW_EMULATOR_HASH:
        description: "Flow Emulator repo commit hash"
        type: string

jobs:
  cadence-emulator:
    runs-on: ubuntu-latest
    steps:
      - name: Save current timestamp to env var
        run: |
            echo "TIMESTAMP=$(date)" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3
        with: 
          path: devex-tests
  
      #########

      - name: Get cadence repo sources
        uses: actions/checkout@v3
        with:
          repository: onflow/cadence
          path: cadence
          ref: ${{ github.event.inputs.CADENCE_HASH }}

      - name: Get Emulator sources
        uses: actions/checkout@v3
        with:
          repository: onflow/flow-emulator
          path: flow-emulator
          ref: ${{ github.event.inputs.FLOW_EMULATOR_HASH }}

      ###

      - uses: actions/setup-go@v1
        with:
          go-version: '1.19'
      
      - name: Install build dependencies 
        run: |
          sudo apt-get update -y 
          sudo apt-get install build-essential zip cmake -y 

      ###

      - name: Replace imports with local sources in emulator project
        run: | 
          cd flow-emulator
          go mod edit -replace github.com/onflow/cadence=../cadence

      - name: Build emulator
        run: |
          cd flow-emulator
          go mod tidy
          go build ./cmd/emulator

      - name: Upload emulator artifacts
        uses: actions/upload-artifact@v3
        with:
          name: flow-emulator
          path: flow-emulator/emulator

      - name: Send slack notification
        if: ${{ failure() }}
        run: >
          curl -X POST -H 'Content-type: application/json' --data 
          '
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "flow-emulator build failed"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "https://github.com/onflow/devex-tests/actions/runs/${{ github.run_id }}"
                }
              }
            ]
          }
          '  
          ${{ secrets.SLACK_WEBHOOK }}
  
