name: Build the emulator with custom Cadence dependency

on:
  workflow_dispatch:
    inputs:
      CADENCE_HASH:
        description: "Cadence repo commit hash"
        type: string
      FLOW_EMULATOR_HASH:
        description: "Flow Emulator repo commit hash"
        type: string

jobs:
  build-emulator:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Save current timestamp to env var
        run: |
            echo "TIMESTAMP=$(date)" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3
        with: 
          path: devex-tests
  
      #########

      - name: Get cadence repo sources
        uses: actions/checkout@v3
        with:
          repository: onflow/cadence
          path: cadence
          ref: ${{ github.event.inputs.CADENCE_HASH }}

      - name: Get Emulator sources
        uses: actions/checkout@v3
        with:
          repository: onflow/flow-emulator
          path: flow-emulator
          ref: ${{ github.event.inputs.FLOW_EMULATOR_HASH }}

      ###

      - uses: actions/setup-go@v1
        with:
          go-version: '1.19'
      
      - name: Install build dependencies 
        run: |
          sudo apt-get update -y 
          sudo apt-get install build-essential zip cmake -y 

      ###

      - name: Replace imports with local sources in emulator project
        run: | 
          cd flow-emulator
          go mod edit -replace github.com/onflow/cadence=../cadence

      - name: Build emulator
        run: |
          cd flow-emulator
          go mod tidy
          go build ./cmd/emulator

  
      - name: Upload emulator artifacts
        uses: actions/upload-artifact@v3
        with:
          name: flow-emulator
          path: flow-emulator/emulator

      # - if: ${{ always() }}
      #   run: |
      #     echo "FLOW_CLI_HASH=${{ github.event.inputs.FLOW_CLI_HASH || 'master' }}" >> $GITHUB_ENV

      # - name: Write result to CSV file
      #   if: ${{ always() }}
      #   uses: gr2m/write-csv-file-action@v1.x
      #   with:
      #     path: devex-tests/results.csv
      #     columns: timestamp,result,cadence version,flow-go version,emulator version,flow-cli version
      #     "timestamp": ${{ env.TIMESTAMP }} 
      #     "result": ${{ job.status }}
      #     "cadence version": ${{ env.CADENCE_HASH }}
      #     "flow-go version": ${{ env.FLOW_GO_HASH }}
      #     "emulator version": ${{ env.FLOW_EMULATOR_HASH }}
      #     "flow-cli version": ${{ github.event.inputs.FLOW_CLI_HASH || 'master' }}  

      # - name: Push updated results.csv file back to main branch
      #   if: ${{ always() }}
      #   run: | 
      #     cd devex-tests
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git add results.csv
      #     git commit -m "results.csv updated"
      #     git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  
