name: integration tests

on:
  workflow_dispatch:
    inputs:
      KITTY_ITEMS_HASH:
        description: "kitty-items commit hash"
        type: string
      FLOW_CLI_HASH:
        description: "flow-cli commit hash"
        type: string
      DEV_WALLET_HASH:
        description: "fcl-dev-wallet commit hash"
        type: string

jobs:
  kitty-items:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    container: cypress/browsers:node16.14.2-slim-chrome103-ff102 #use arm64 arch on Apple M1 chips when running locally
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          path: checkout
      
      - name: Get flow cli sources
        uses: actions/checkout@v3
        with:
          repository: onflow/flow-cli
          path: flow-cli
          ref: ${{ github.event.inputs.FLOW_CLI_HASH }}

      # - name: Setup git alias for cloning PR
      #   run: git config --global alias.pr '!f() { git fetch -fu ${2:-origin} refs/pull/$1/head:pr/$1 && git checkout pr/$1; }; f'

      - name: Get dev-wallet sources
        uses: actions/checkout@v3
        with:
          repository: onflow/fcl-dev-wallet
          path: fcl-dev-wallet
          ref: ${{ github.event.inputs.DEV_WALLET_HASH }}

      - name: Get kitty-items sources
        uses: actions/checkout@v3
        with:
          repository: onflow/kitty-items
          path: kitty-items
          ref: ${{ github.event.inputs.KITTY_ITEMS_HASH }}

      - uses: actions/setup-go@v1
        with:
          go-version: '1.18'
      
      - name: Install build dependencies 
        run: apt-get update -y && apt-get install build-essential zip -y 
      
      - name: Build fcl-dev-wallet
        run: |
          cd fcl-dev-wallet 
          npm install
          npm run bundle 
          npm run zip 
          npm run config

      - name: Replace dev wallet import in flow-cli project
        run: cd flow-cli && go mod edit -replace github.com/onflow/fcl-dev-wallet=../fcl-dev-wallet
          # run: sed -i "s/$search/$replace/" $filename
      
      # - name: Install Flow CLI
      #   run: | 
      #     sh -ci "$(curl -fsSL https://storage.googleapis.com/flow-cli/install.sh)" &&
      #     echo "/root/.local/bin:/github/home/.local/bin" >> $GITHUB_PATH
      #     echo $HOME &&
      #     ls -l $HOME/.local/bin &&
      #     chmod a+r $HOME/.local/bin/flow &&
      #     ls -l $HOME/.local/bin &&
      #     $HOME/.local/bin/flow version

      - name: Build flow-cli
        run: cd flow-cli && make versioned-binaries

      - name: Copy flow binary
        run: cp flow-cli/cmd/flow/flow-x86_64-linux- /usr/local/bin/flow && ls /usr/local/bin/flow

      - name: Build Kitty Items
        run: ls && cd kitty-items && npm i 

      - name: Cypress run emulator
      uses: cypress-io/github-action@v4
      with:
        start: npm run dev:emulator
        wait-on: http://localhost:3001
        spec: cypress/e2e/emulator.cy.js
        record: true
      env:
        CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-screenshots
        path: cypress/screenshots
    # Test run video was always captured, so this action uses "always()" condition
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: cypress-videos
        path: cypress/videos

  # scratch:
  #   runs-on: ubuntu-latest
  #   steps:
      
  #     - name: Replace dev wallet import in flow-cli project
  #       run: cd flow-cli && go mod edit -replace github.com/onflow/fcl-dev-wallet=../fcl-dev-wallet
  #       # run: sed -i "s/$search/$replace/" $filename
  
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/setup-go@v1
  #       with:
  #         go-version: '1.18'
  #     - name: Build and install flow-cli
  #       if: ${{ github.event.inputs.FLOW_CLI_HASH }}
  #       run: |
  #         cd flow-cli && 
  #         make versioned-binaries &&
  #         cp cmd/flow/flow-x86_64-linux- /usr/local/bin/flow && 
  #         ls /usr/local/bin/flow
  #     - name: Build dev-wallet
  #       run: cd fcl-dev-wallet && npm install && npm run bundle
  #     - name: Build kitty-items
  #       run: cd kitty-items && npm install && npx lerna exec npm install
  # start:
  #   runs-on: ubuntu-latest
  #   steps:
  #     # - name: pm2 -h
  #     #   run: pm2 -h
  #     # - name: npx pm2 -h
  #     #   run: cd kitty-items && npx pm2 -h
  #     # - name: Add aliases
  #     #   run: echo "alias flow=$(pwd)/flow-cli/cmd/flow/flow-x86_64-linux-" > ~/.bash_aliases
  #     # - name: Add aliases2
  #     #   run: echo "alias flow=$(pwd)/flow-cli/cmd/flow/flow-x86_64-linux-" >> ~/.bashrc
  #     - name: Copy flow binary
  #       run: cp flow-cli/cmd/flow/flow-x86_64-linux- /usr/local/bin/flow && ls /usr/local/bin/flow
  #     - name: Start kitty-items, dev-wallet, emulator
  #       run: cd kitty-items && npm run dev:emulator & cd kitty-items && ./test.sh #while ! curl --output /dev/null --silent --head --fail http://localhost:3001; do sleep 1 && echo -n .; done;
  # build-int:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
  #     - uses: actions/setup-go@v1
  #       with:
  #         go-version: '1.18'
  #     - name: Build Binaries
  #       run: make versioned-binaries
  # run-test:
  #   runs-on: ubuntu-latest
  #   steps:    
  #     # - name: Run flow command
  #     #   run: cmd/flow/flow-x86_64-linux-
  #     # - name: Start emulator and dev-wallet
  #     #   run: cmd/flow/flow-x86_64-linux- emulator && curl http://localhost:8888 
  #     - name: Start emulator dev-wallet
  #       run: |
  #         node test.js &&
  #         curl http://localhost:8888 &&
  #         curl http://localhost:8701
          
  #     # sleep 5 &&
  #     # curl http://localhost:8701
  
